### ISSUE TITLE
VRT File

### ISSUE THREAD

**Issue by NGuinard** [opensolarmap/solml#1]
Hello Michel,

First, I would like to thank you for this very interesting project which is very helpful to learn about both how to use satellite imagery and how to build machine learning models with it.

I would like to ask you a question concerning **how you built you VRT file**. I tried to do it from a TIFF file using the following gdal command : _gdalbuildvrt file.tiff file.vrt_. So I tried to find a GeoTIFF file that I could use to build my VRT File but I didn't get to it.

Could you help me on this issue ? What source did you use to get a TIFF file that enabled you to build your VRT file ?

Thank you very much in advance !
Best regards,
Nicolas.

**Comment by michelbl** [comment]
Thanks !
I've written the VRT files by hand. For example (replace %url% by the url of the tile server and %cache_dir% by the cache directory) : 
```
<GDAL_WMS>
    <Service name="TMS">
        <ServerUrl>%url%</ServerUrl>
    </Service>
    <DataWindow>
        <UpperLeftX>-20037508.34</UpperLeftX>
        <UpperLeftY>20037508.34</UpperLeftY>
        <LowerRightX>20037508.34</LowerRightX>
        <LowerRightY>-20037508.34</LowerRightY>
        <TileLevel>19</TileLevel>
        <TileCountX>1</TileCountX>
        <TileCountY>1</TileCountY>
        <YOrigin>top</YOrigin>
    </DataWindow>
    <Projection>EPSG:3857</Projection>
    <BlockSizeX>256</BlockSizeX>
    <BlockSizeY>256</BlockSizeY>
    <BandsCount>3</BandsCount>
    <Cache>
      <Path>%cache_dir%</Path>
      <Depth>2</Depth>
      <Extension>.png</Extension>
    </Cache>
</GDAL_WMS>
```
