### ISSUE TITLE
Getting Started?

### ISSUE THREAD

**Issue by kumarravigithub** [opensolarmap/solml#3]
Can you include a small writeup on Getting Started / How to Use? I have installed everything successfully as instructed in README.md, now don't know where to begin.

**Comment by JoshuaC3** [comment]
Same here!

**Comment by michelbl** [comment]
Thanks for your interest for that project! I've added the data needed for the training, I added the blogposts that describe this project (unfortunately they are in french) and I added a small getting started section in the readme. Please do not hesitate to point the things that are not clear.
